# Autogenerated wrapper script for libtirpc_jll for armv7l-linux-musleabihf
export libtirpc

JLLWrappers.@generate_wrapper_header("libtirpc")
JLLWrappers.@declare_library_product(libtirpc, "libtirpc.so.3")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtirpc,
        "lib/libtirpc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
